// Generic chat store. Holds the in-memory state (messages, in-flight
// pending parts, sending flag, hydration) and drives a streamed turn —
// optimistic user bubble first, then assistant parts as chunks arrive.
//
// The orchestrator chat and the delegate run page are both instances of
// this class with different `loadHistory` / `send` / `onTurnFinalized`
// implementations. ChatSurface and ChatInput accept any ChatStore via
// prop, so the same Svelte components render both surfaces.

import type {
  ChatStreamPart,
  SkillInvocationMeta,
  TextPart,
  ToolPart,
  UIAssistantMessage,
  UIChatTurn,
  UIMessagePart,
  UIUserMessage,
} from "$lib/types/chat";

export interface ChatAttachmentInput {
  filename: string;
  mediaType: string;
  sizeBytes: number;
  dataBase64: string;
}

export interface ChatSendInput {
  text: string;
  attachments?: ChatAttachmentInput[];
  /** Set when the send originated from a recognised `/skill`
   *  invocation. Caller (ChatInput) is responsible for detection and
   *  materialisation; the store just propagates the metadata to the
   *  user-bubble and the agent loop. */
  skillInvocation?: SkillInvocationMeta;
  /** Substituted skill body, joined to `text` when forwarded to the
   *  model. Persisted on the user message so the drawer can render
   *  it after a reload. */
  skillExpandedBody?: string;
}

export interface ChatStoreOptions {
  /** Load the finalized turn history that hydrates this surface. */
  loadHistory: () => Promise<UIChatTurn[]>;
  /** Stream a fresh turn. Receives the user's send and returns the
   *  assistant reply as an AsyncIterable of SDK TextStreamPart events. */
  send: (input: ChatSendInput) => AsyncIterable<ChatStreamPart>;
  /** Optional persistence hook — fires once when a turn finalizes,
   *  with the user-side message and the assembled assistant message.
   *  The orchestrator store writes both to SQLite here. The delegate
   *  store persists incrementally inside `send` (so chunks survive a
   *  crash mid-stream), making this hook a no-op for it. */
  onTurnFinalized?: (
    userMsg: UIUserMessage,
    assistantMsg: UIAssistantMessage,
  ) => Promise<void> | void;
}

function errorToText(error: unknown): string {
  if (error instanceof Error) return error.message;
  if (typeof error === "string") return error;
  try {
    return JSON.stringify(error);
  } catch {
    return String(error);
  }
}

/** Collapse in-flight part states to terminal ones so the assistant
 *  bubble renders statically once the streaming wrapper unmounts. */
function finaliseStreamingParts(parts: UIMessagePart[]): UIMessagePart[] {
  return parts.map((p) => {
    if (p.type === "text" && p.state === "streaming") {
      return { ...p, state: "done" } satisfies TextPart;
    }
    if (p.type !== "text" && p.type !== "step-start") {
      if (p.state === "input-streaming") {
        return {
          ...p,
          state: "output-error",
          errorText: "Stream ended before tool input was received.",
        } satisfies ToolPart;
      }
      if (p.state === "input-available") {
        return {
          ...p,
          state: "output-error",
          errorText: "Stream ended before tool output arrived.",
        } satisfies ToolPart;
      }
    }
    return p;
  });
}

/** Build an assistant turn that always shows an error message, regardless
 *  of what already streamed. Without this, an early error after only a
 *  step-start would produce an empty assistant bubble. */
function buildAssistantWithError(
  pendingParts: UIMessagePart[],
  errorText: string,
): UIAssistantMessage {
  const errorPart: TextPart = {
    type: "text",
    text: `Error: ${errorText}`,
    state: "done",
  };
  const finalisedExisting = finaliseStreamingParts(pendingParts);
  const filtered = finalisedExisting.filter((p) => p.type !== "step-start");
  return {
    id: `local-assistant-${Date.now()}`,
    role: "assistant",
    parts: [...filtered, errorPart],
    createdAt: new Date().toISOString(),
  };
}

/** Queue priority levels — patterned after claude-code's REPL queue
 *  manager. Higher priorities drain first; within the same priority
 *  FIFO order is preserved.
 *  - `user`: messages typed by the human user. Always processed first
 *    so the human's input never gets starved by autonomous notifications.
 *  - `system-event`: synthetic user-role messages generated by the app
 *    itself (today: post-delegate-completion notifications). Drains
 *    after any pending user messages so an explicit user request takes
 *    precedence over a background completion the orchestrator might
 *    otherwise react to first. */
type QueuePriority = "user" | "system-event";

interface SkillContext {
  invocation: SkillInvocationMeta;
  /** Async hook that runs AFTER the user bubble is painted but
   *  BEFORE the model stream starts. Shows the permission panel
   *  (which itself awaits user input) and runs the shell-block
   *  expansion. Returns the materialised body, or null if the user
   *  denied something and there's no usable expansion to send. */
  materialise: () => Promise<string | null>;
}

export interface QueuedMessage {
  priority: QueuePriority;
  /** Synthetic ID of the optimistic user bubble already painted into
   *  `#messages`. The drain loop uses this to know which bubble belongs
   *  to which queued turn — we don't repaint when dequeueing. */
  bubbleId: string;
  text: string;
  attachments: ChatAttachmentInput[];
  /** Optional skill context to materialise just before the LLM call
   *  for this queue item. Materialisation is deferred to executeTurn
   *  rather than enqueue so permission prompts fire in turn order
   *  rather than all upfront when the user queues several skills. */
  skillContext?: SkillContext;
}

export class ChatStore {
  #messages = $state<UIChatTurn[]>([]);
  #pendingParts = $state<UIMessagePart[]>([]);
  #partIndexById = new Map<string, number>();
  #sending = $state<boolean>(false);
  #hydrated = $state<boolean>(false);
  #hydrating = $state<boolean>(false);
  #hydrationError = $state<string | null>(null);
  // External streaming buffer — used by passive viewers (e.g. the
  // run-detail page when the orchestrator is the one driving the
  // delegate). Tokens fed via `appendExternalText` render as a
  // streaming assistant bubble below the persisted history; the
  // buffer clears once the corresponding chunk persists and the
  // viewer calls `clearExternalText()`. Distinct from #pendingParts
  // which is owned by the local send() pump.
  #externalText = $state<string>("");
  // Post-turn message queue. Messages typed while a turn is in flight
  // get pushed here; the drain loop in `send()` consumes them one at
  // a time as soon as the active turn finishes. User-facing meaning:
  // the chat input is never blocked — the user can keep typing while
  // a delegate is running, and each typed message becomes the next
  // orchestrator turn in sequence. See claude-code's REPL queue
  // manager for the inspiration; our version drains between turns
  // rather than between tool calls.
  #queue = $state<QueuedMessage[]>([]);
  readonly #opts: ChatStoreOptions;

  constructor(opts: ChatStoreOptions) {
    this.#opts = opts;
  }

  get messages(): UIChatTurn[] {
    return this.#messages;
  }
  get pendingParts(): UIMessagePart[] {
    if (this.#pendingParts.length > 0) return this.#pendingParts;
    if (this.#externalText.length > 0) {
      return [
        { type: "text", text: this.#externalText, state: "streaming" },
      ];
    }
    return this.#pendingParts;
  }
  get hasPending(): boolean {
    return (
      this.#pendingParts.length > 0 ||
      this.#sending ||
      this.#externalText.length > 0
    );
  }
  get sending(): boolean {
    return this.#sending;
  }
  /** Number of messages typed while a turn was in flight that are
   *  waiting to become their own turn. Shown by the UI as a small
   *  badge next to the composer so the user can see what's queued. */
  get queuedCount(): number {
    return this.#queue.length;
  }
  get hydrated(): boolean {
    return this.#hydrated;
  }
  get hydrating(): boolean {
    return this.#hydrating;
  }
  get hydrationError(): string | null {
    return this.#hydrationError;
  }

  async hydrate(): Promise<void> {
    if (this.#hydrated || this.#hydrating) return;
    this.#hydrating = true;
    this.#hydrationError = null;
    try {
      this.#messages = await this.#opts.loadHistory();
      this.#hydrated = true;
    } catch (err) {
      this.#hydrationError =
        err instanceof Error ? err.message : "Failed to load history";
      this.#hydrated = true;
    } finally {
      this.#hydrating = false;
    }
  }

  /** Replace the in-memory messages with whatever `loadHistory` returns
   *  next time it's called. Used by the run page to reconcile after a
   *  send completes, in case the persisted chunks differ from what we
   *  reconstructed in memory. */
  async refresh(): Promise<void> {
    try {
      this.#messages = await this.#opts.loadHistory();
      this.#hydrationError = null;
    } catch (err) {
      // eslint-disable-next-line no-console
      console.warn("[chat-store] refresh failed", err);
    }
  }

  reset(): void {
    this.#messages = [];
    this.#pendingParts = [];
    this.#partIndexById = new Map();
    this.#sending = false;
    this.#hydrated = false;
    this.#hydrating = false;
    this.#hydrationError = null;
    this.#externalText = "";
    this.#queue = [];
  }

  /** Discard everything still in the post-turn queue. The current
   *  in-flight turn (if any) keeps running — call abort APIs on its
   *  generator if you need to stop it too (not currently exposed). */
  clearQueue(): void {
    this.#queue = [];
  }

  /** Drain every queued `system-event` item (typically background
   *  delegate completion notifications) and return them. User-typed
   *  items are left in the queue untouched. Used by the orchestrator
   *  loop's `prepareStep` callback to inject mid-turn notifications
   *  into the next LLM step's message list, so completions arriving
   *  while the orchestrator is reasoning get reflected immediately
   *  instead of waiting for the current turn to finish.
   *
   *  Returns the items in queue order. The optimistic bubbles for
   *  these items are already painted into `#messages`; the caller is
   *  responsible only for translating them into model messages for
   *  the LLM. */
  consumePendingSystemEvents(): QueuedMessage[] {
    const events: QueuedMessage[] = [];
    const remaining: QueuedMessage[] = [];
    for (const item of this.#queue) {
      if (item.priority === "system-event") events.push(item);
      else remaining.push(item);
    }
    if (events.length === 0) return events;
    this.#queue = remaining;
    return events;
  }

  /** Append a token delta from an external source (e.g. an orchestrator-driven
   *  delegate run observed by a passive viewer). Renders as a streaming
   *  assistant bubble until the caller clears it. */
  appendExternalText(delta: string): void {
    if (!delta) return;
    this.#externalText += delta;
  }

  /** Replace the external streaming buffer wholesale. Used by passive
   *  viewers seeding from the module-scoped live-text buffer on mount
   *  (see `getLiveText` in run-events.ts) — replacing rather than
   *  appending avoids double-counting deltas that arrived between the
   *  subscribe-listener registration and the seed call. */
  setExternalText(text: string): void {
    this.#externalText = text;
  }

  /** Discard the external streaming buffer. Typically called when the
   *  corresponding chunk has been persisted to the DB and reloaded into
   *  the store's regular history. */
  clearExternalText(): void {
    this.#externalText = "";
  }

  /** Submit a user message. The bubble is painted optimistically into
   *  the chat immediately; the actual orchestrator turn either runs now
   *  (if nothing's in flight) or runs after the current turn finishes
   *  (via the post-turn priority queue). Either way the user can keep
   *  typing the next message without waiting. */
  async send(
    text: string,
    attachments: ChatAttachmentInput[] = [],
    skillContext?: SkillContext,
  ): Promise<void> {
    const trimmed = text.trim();
    if (!trimmed && attachments.length === 0) return;

    this.#enqueue({
      priority: "user",
      text: trimmed,
      attachments,
      systemEvent: false,
      skillContext,
    });

    if (this.#sending) return;
    await this.#drain();
  }

  /** Push a system-generated user-role message into the queue. Used by
   *  the post-delegate-completion notification flow: when a background
   *  delegate finishes, the chat module subscribes to the completion
   *  event and calls this to fire a new orchestrator turn carrying the
   *  notification text. Priority is `system-event`, so a user message
   *  arriving after this still processes first.
   *
   *  Fire-and-forget — kicks off the drain if no turn is in flight;
   *  otherwise the existing drain loop picks it up next. */
  enqueueSystemNotification(content: string): void {
    const trimmed = content.trim();
    if (!trimmed) return;
    this.#enqueue({
      priority: "system-event",
      text: trimmed,
      attachments: [],
      systemEvent: true,
    });
    if (this.#sending) return;
    void this.#drain().catch((err) => {
      // eslint-disable-next-line no-console
      console.error("[chat-store] system-event drain failed:", err);
    });
  }

  /** Paint the optimistic bubble + push onto the queue. Returns the
   *  bubble id so callers can correlate if they need to. */
  #enqueue(opts: {
    priority: QueuePriority;
    text: string;
    attachments: ChatAttachmentInput[];
    systemEvent: boolean;
    skillContext?: SkillContext;
  }): string {
    const bubbleId = `local-${opts.systemEvent ? "sysevent" : "user"}-${Date.now()}-${Math.random()
      .toString(36)
      .slice(2, 6)}`;
    const userMessage: UIUserMessage = {
      id: bubbleId,
      role: "user",
      content: opts.text,
      createdAt: new Date().toISOString(),
      attachments: opts.attachments.length
        ? opts.attachments.map((a) => ({
            filename: a.filename,
            mediaType: a.mediaType,
            sizeBytes: a.sizeBytes,
          }))
        : undefined,
      skillInvocation: opts.skillContext?.invocation,
      skillStatus: opts.skillContext ? "running" : undefined,
      ...(opts.systemEvent ? { systemEvent: true } : {}),
    };
    this.#messages = [...this.#messages, userMessage];
    this.#queue = [
      ...this.#queue,
      {
        priority: opts.priority,
        bubbleId,
        text: opts.text,
        attachments: opts.attachments,
        skillContext: opts.skillContext,
      },
    ];
    return bubbleId;
  }

  /** Drain the queue, picking highest-priority items first (user before
   *  system-event), FIFO within a priority. Runs until empty. The
   *  `#sending` flag is owned by `#executeTurn`, so concurrent calls to
   *  `#drain()` are safe — the second one's `while` loop will see an
   *  empty queue once the first finishes. */
  async #drain(): Promise<void> {
    while (true) {
      const next = this.#dequeueHighestPriority();
      if (!next) return;
      await this.#executeTurn(next);
    }
  }

  /** Find and remove the first item with the highest priority present
   *  in the queue. Returns null when the queue is empty. Priority order:
   *  user > system-event. Always returns a new array on success so
   *  Svelte reactivity fires. */
  #dequeueHighestPriority(): QueuedMessage | null {
    const order: QueuePriority[] = ["user", "system-event"];
    for (const priority of order) {
      const idx = this.#queue.findIndex((q) => q.priority === priority);
      if (idx >= 0) {
        const item = this.#queue[idx];
        this.#queue = [
          ...this.#queue.slice(0, idx),
          ...this.#queue.slice(idx + 1),
        ];
        return item;
      }
    }
    return null;
  }

  async #executeTurn(item: QueuedMessage): Promise<void> {
    this.#sending = true;
    this.#pendingParts = [];
    this.#partIndexById = new Map();

    const userMessage =
      (this.#messages.find((m) => m.id === item.bubbleId) as
        | UIUserMessage
        | undefined) ?? {
        id: item.bubbleId,
        role: "user",
        content: item.text,
        createdAt: new Date().toISOString(),
      };

    // Materialise the skill body — Phase 3 substitution + Phase 4
    // shell expansion + permission prompts. Runs after dequeue (rather
    // than at send/enqueue time) so permission prompts fire in queue
    // order if the user has chained several skill invocations.
    let skillExpandedBody: string | undefined;
    if (item.skillContext) {
      const result = await item.skillContext.materialise();
      const resolvedBody = result !== null ? result : undefined;
      if (resolvedBody) skillExpandedBody = resolvedBody;
      this.#messages = this.#messages.map((m) =>
        m.id === item.bubbleId
          ? {
              ...m,
              skillStatus: "done",
              ...(resolvedBody ? { skillExpandedBody: resolvedBody } : {}),
            }
          : m,
      );
    }

    let finalised = false;
    let assistantMessage: UIAssistantMessage | null = null;
    try {
      for await (const chunk of this.#opts.send({
        text: item.text,
        attachments: item.attachments,
        skillInvocation: item.skillContext?.invocation,
        skillExpandedBody,
      })) {
        // Reducer maps SDK TextStreamPart events into UIMessagePart updates.
        // Field-name diffs vs our legacy shape:
        //   - text-delta uses `.text`, not `.delta`
        //   - tool-input-start uses `.id`, not `.toolCallId`
        //   - tool-input-delta uses `.id` + `.delta`
        //   - `tool-call` replaces `tool-input-available`
        //   - `tool-result` replaces `tool-output-available`
        //   - `tool-error` replaces `tool-output-error`, payload field `.error`
        //   - error uses `.error: unknown`, not `.errorText: string`
        if (chunk.type === "start") {
          this.#pendingParts = [];
          this.#partIndexById = new Map();
        } else if (chunk.type === "start-step") {
          this.#pendingParts = [
            ...this.#pendingParts,
            { type: "step-start" },
          ];
        } else if (chunk.type === "text-start") {
          const idx = this.#pendingParts.length;
          this.#pendingParts = [
            ...this.#pendingParts,
            { type: "text", text: "", state: "streaming" } satisfies TextPart,
          ];
          this.#partIndexById.set(chunk.id, idx);
        } else if (chunk.type === "text-delta") {
          const idx = this.#partIndexById.get(chunk.id);
          if (idx !== undefined) {
            const parts = [...this.#pendingParts];
            const part = parts[idx] as TextPart;
            parts[idx] = { ...part, text: part.text + chunk.text };
            this.#pendingParts = parts;
          }
        } else if (chunk.type === "text-end") {
          const idx = this.#partIndexById.get(chunk.id);
          if (idx !== undefined) {
            const parts = [...this.#pendingParts];
            const part = parts[idx] as TextPart;
            parts[idx] = { ...part, state: "done" };
            this.#pendingParts = parts;
          }
        } else if (chunk.type === "tool-input-start") {
          const idx = this.#pendingParts.length;
          this.#pendingParts = [
            ...this.#pendingParts,
            {
              type: `tool-${chunk.toolName}`,
              toolCallId: chunk.id,
              state: "input-streaming",
            } satisfies ToolPart,
          ];
          this.#partIndexById.set(chunk.id, idx);
        } else if (chunk.type === "tool-call") {
          const existing = this.#partIndexById.get(chunk.toolCallId);
          if (existing !== undefined) {
            const parts = [...this.#pendingParts];
            const part = parts[existing] as ToolPart;
            parts[existing] = {
              ...part,
              state: "input-available",
              input: chunk.input,
            };
            this.#pendingParts = parts;
          } else {
            const idx = this.#pendingParts.length;
            this.#pendingParts = [
              ...this.#pendingParts,
              {
                type: `tool-${chunk.toolName}`,
                toolCallId: chunk.toolCallId,
                state: "input-available",
                input: chunk.input,
              } satisfies ToolPart,
            ];
            this.#partIndexById.set(chunk.toolCallId, idx);
          }
        } else if (chunk.type === "tool-result") {
          const idx = this.#partIndexById.get(chunk.toolCallId);
          if (idx !== undefined) {
            const parts = [...this.#pendingParts];
            const part = parts[idx] as ToolPart;
            parts[idx] = {
              ...part,
              state: "output-available",
              output: chunk.output,
            };
            this.#pendingParts = parts;
          }
        } else if (chunk.type === "tool-error") {
          const idx = this.#partIndexById.get(chunk.toolCallId);
          if (idx !== undefined) {
            const parts = [...this.#pendingParts];
            const part = parts[idx] as ToolPart;
            parts[idx] = {
              ...part,
              state: "output-error",
              errorText: errorToText(chunk.error),
            };
            this.#pendingParts = parts;
          }
        } else if (chunk.type === "finish") {
          assistantMessage = {
            id: `local-assistant-${Date.now()}`,
            role: "assistant",
            parts: this.#pendingParts,
            createdAt: new Date().toISOString(),
          };
          this.#messages = [...this.#messages, assistantMessage];
          finalised = true;
          break;
        } else if (chunk.type === "error") {
          const errorText = errorToText(chunk.error);
          // eslint-disable-next-line no-console
          console.error("[chat-store] error chunk:", errorText);
          assistantMessage = buildAssistantWithError(
            this.#pendingParts,
            errorText,
          );
          this.#messages = [...this.#messages, assistantMessage];
          finalised = true;
          break;
        }
      }
    } catch (err) {
      const reason = err instanceof Error ? err.message : "Stream failed";
      // eslint-disable-next-line no-console
      console.error("[chat-store] stream threw:", err);
      assistantMessage = buildAssistantWithError(this.#pendingParts, reason);
      this.#messages = [...this.#messages, assistantMessage];
      finalised = true;
    } finally {
      const carried = this.#pendingParts;
      this.#sending = false;
      this.#pendingParts = [];
      this.#partIndexById = new Map();
      if (!finalised) {
        // eslint-disable-next-line no-console
        console.warn(
          "[chat-store] stream ended without finish/error — pending parts:",
          carried.length,
        );
        const parts: UIMessagePart[] =
          carried.length > 0
            ? finaliseStreamingParts(carried)
            : [
                {
                  type: "text",
                  text: "Stream ended unexpectedly.",
                  state: "done",
                },
              ];
        assistantMessage = {
          id: `local-assistant-${Date.now()}`,
          role: "assistant",
          parts,
          createdAt: new Date().toISOString(),
        };
        this.#messages = [...this.#messages, assistantMessage];
      }
    }

    if (assistantMessage && this.#opts.onTurnFinalized) {
      try {
        await this.#opts.onTurnFinalized(userMessage, assistantMessage);
      } catch (err) {
        // eslint-disable-next-line no-console
        console.warn("[chat-store] onTurnFinalized failed", err);
      }
    }
  }
}
