<script lang="ts">
  import { onDestroy } from "svelte";
  import MarkdownView from "$lib/components/chat/MarkdownView.svelte";
  import AttachmentChip from "$lib/components/chat/AttachmentChip.svelte";
  import ToolPartView from "$lib/components/chat/ToolPartView.svelte";
  import { displayName } from "$lib/skills/display";
  import type {
    SkillInvocationMeta,
    SkillRunStatus,
    UIMessagePart,
    ToolPart,
  } from "$lib/types/chat";

  interface Props {
    role: "user" | "assistant";
    content?: string;
    parts?: UIMessagePart[];
    messageId?: string;
    /** Threaded to ToolPartView so a module tool's cockpit entry can
     *  resolve its live per-conversation state on click. Omitted (e.g. on a
     *  delegate run surface, or before a draft session has a real id) just
     *  means clicking a module tool re-opens the panel without replaying
     *  that specific call. */
    conversationId?: string;
    streaming?: boolean;
    errored?: boolean;
    partial?: boolean;
    attachments?: Array<{ filename: string; mediaType: string; sizeBytes: number }>;
    /** Set on user bubbles whose content invoked a `/skill`. Renders
     *  a chip + drawer above the bubble. */
    skillInvocation?: SkillInvocationMeta;
    /** Materialised skill body — what the model received. Surfaced
     *  when the chip is expanded. */
    skillExpandedBody?: string;
    /** Lifecycle of the skill invocation — "running" shows a
     *  shimmering indicator beneath the bubble. */
    skillStatus?: SkillRunStatus;
    /** When true on a user message, this was generated by the system
     *  (e.g. a background-delegate completion notification) rather than
     *  typed by the human. Renders distinctly so the user understands
     *  the provenance. Ignored for assistant messages. */
    systemEvent?: boolean;
  }

  const {
    role,
    content = "",
    parts = [],
    messageId,
    conversationId,
    streaming = false,
    errored = false,
    partial = false,
    attachments,
    skillInvocation,
    skillExpandedBody,
    skillStatus,
    systemEvent = false,
  }: Props = $props();

  const hasAttachments = $derived(!!attachments && attachments.length > 0);

  // ─── Paced character reveal ──────────────────────────────────────────
  // Applied to the active streaming TextPart. We track the last text part
  // that is in 'streaming' state and pace it via rAF.
  // For non-streaming (history or done), all text is shown immediately.

  const activeStreamingText = $derived.by(() => {
    if (!streaming) return null;
    for (let i = parts.length - 1; i >= 0; i--) {
      const p = parts[i];
      if (p.type === "text" && p.state === "streaming") return p.text;
    }
    return null;
  });

  let displayed = $state("");
  let pacingFrame: number | null = null;
  let lastEmitMs = 0;
  const EMIT_INTERVAL_MS = 32;

  function stopPacing() {
    if (pacingFrame !== null) {
      cancelAnimationFrame(pacingFrame);
      pacingFrame = null;
    }
  }

  function tickPacing(now: DOMHighResTimeStamp) {
    pacingFrame = null;
    const target = activeStreamingText ?? "";
    const remaining = target.length - displayed.length;
    if (remaining <= 0) return;

    if (now - lastEmitMs >= EMIT_INTERVAL_MS) {
      const charsPerEmit = Math.min(16, Math.max(2, Math.floor(remaining / 30) * 2 + 2));
      displayed = target.slice(0, displayed.length + charsPerEmit);
      lastEmitMs = now;
    }
    pacingFrame = requestAnimationFrame(tickPacing);
  }

  $effect(() => {
    void activeStreamingText;
    void streaming;

    if (!streaming || activeStreamingText === null) {
      stopPacing();
      displayed = "";
      return;
    }

    if (displayed.length < activeStreamingText.length && pacingFrame === null) {
      lastEmitMs = performance.now();
      pacingFrame = requestAnimationFrame(tickPacing);
    }
  });

  onDestroy(stopPacing);

  const isAnimating = $derived(
    streaming && activeStreamingText !== null &&
    (activeStreamingText.length > displayed.length || activeStreamingText.length > 0),
  );

  const showThinking = $derived(
    streaming &&
    !parts.some(
      (p) =>
        (p.type === "text" && p.text.length > 0) ||
        (p.type !== "text" && p.type !== "step-start"),
    ),
  );
</script>

<div
  class="row"
  class:user={role === "user"}
  class:assistant={role === "assistant"}
  class:system-event={systemEvent && role === "user"}
  data-msg-id={messageId ?? ""}
>
  {#if hasAttachments}
    <div class="attachments">
      {#each attachments! as att (att.filename)}
        <AttachmentChip
          filename={att.filename}
          mediaType={att.mediaType}
          sizeBytes={att.sizeBytes}
        />
      {/each}
    </div>
  {/if}

  {#if role === "user"}
    {#if content}
      <div class="bubble" class:errored>
        {#if systemEvent}
          <div class="system-event-tag">System event</div>
        {/if}
        <div class="user-text">{content}</div>
      </div>
    {/if}
    {#if skillInvocation && skillStatus === "running"}
      <div class="running-skill">
        <span class="running-label">Running skill</span>
        <span class="skill-shimmer"
          >/{displayName(skillInvocation.source, skillInvocation.name)}</span
        >
      </div>
    {/if}
  {:else}
    <div
      class="assistant-content"
      class:errored
      class:streaming-anchor={streaming}
    >
      {#if showThinking}
        <div class="thinking-row">
          <span class="thinking-dot"></span>
          <span class="thinking-label">Thinking</span>
        </div>
      {:else}
        {#each parts as part, i (i)}
          {#if part.type === "text"}
            {#if part.state === "streaming"}
              <MarkdownView content={displayed} streaming={isAnimating} />
            {:else}
              <MarkdownView content={part.text} streaming={false} />
            {/if}
          {:else if part.type === "step-start"}
            <!-- invisible for now -->
          {:else}
            <div class="tool-calls" data-testid="chat-message-tool-calls">
              <ToolPartView part={part as ToolPart} {conversationId} />
            </div>
          {/if}
        {/each}
      {/if}
      {#if partial && !streaming}
        <div class="footnote">(disconnected before completing)</div>
      {/if}
    </div>
  {/if}
</div>

<style>
  .row {
    display: flex;
    flex-direction: column;
    gap: 0.6em;
    margin: 0;
    width: 100%;
  }
  .row.user {
    align-items: flex-end;
  }
  .row.assistant {
    align-items: flex-start;
  }
  /* System-event user messages (post-delegate-completion notifications)
   * render full-width, muted, and tagged so the user can distinguish
   * them from their own input. They still go through the user-bubble
   * code path because the AI SDK sees them as user-role turns. */
  .row.user.system-event {
    align-items: stretch;
  }
  .row.user.system-event .bubble {
    max-width: 100%;
    background: var(--bg-elevated, var(--bg));
    border: 1px dashed var(--border);
    color: var(--text-muted);
    font-size: 0.86em;
    font-weight: 400;
  }
  .system-event-tag {
    display: inline-block;
    margin-bottom: 0.4em;
    padding: 0.1em 0.5em;
    font-size: 0.74em;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: var(--text-faint);
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 4px;
  }
  .bubble {
    max-width: 75%;
    padding: 0.85em 1.4em;
    border-radius: 22px;
    background: var(--bubble-user-bg);
    color: var(--text);
    font-size: var(--text-body);
    font-weight: 300;
    line-height: 1.7;
    word-break: break-word;
    overflow-wrap: break-word;
  }
  .bubble.errored {
    color: var(--danger-text);
  }
  .assistant-content {
    width: 100%;
    color: var(--text);
    font-size: var(--text-body);
    font-weight: 300;
    line-height: 1.75;
  }
  .assistant-content.streaming-anchor {
    min-height: 80vh;
  }
  .assistant-content.errored {
    color: var(--danger-text);
  }
  .user-text {
    white-space: pre-wrap;
    word-wrap: break-word;
  }
  .attachments {
    display: flex;
    flex-wrap: wrap;
    gap: 0.6em;
    max-width: 75%;
  }
  .row.user .attachments {
    justify-content: flex-end;
  }
  .row.assistant .attachments {
    max-width: 100%;
  }
  .thinking-row {
    display: flex;
    align-items: center;
    gap: 0.55em;
  }
  .thinking-dot {
    display: inline-block;
    width: 0.7em;
    height: 0.7em;
    background: currentColor;
    border-radius: 50%;
    animation: ball-pulse 1s ease-in-out infinite;
    will-change: transform, opacity;
    flex-shrink: 0;
  }
  @keyframes ball-pulse {
    0%, 100% { transform: scale(1); opacity: 0.85; }
    50% { transform: scale(0.7); opacity: 0.45; }
  }
  .thinking-label {
    font-style: italic;
    font-size: var(--text-meta);
    line-height: 1.65;
    background: linear-gradient(
      90deg,
      var(--text-faint) 0%,
      var(--text) 50%,
      var(--text-faint) 100%
    );
    background-size: 200% 100%;
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
    color: transparent;
    animation: thinking-shimmer 2.4s ease-in-out infinite;
  }
  @keyframes thinking-shimmer {
    0% { background-position: 200% 0; }
    100% { background-position: -200% 0; }
  }
  @media (prefers-reduced-motion: reduce) {
    .thinking-dot { animation: none; opacity: 0.6; }
    .thinking-label {
      animation: none;
      -webkit-text-fill-color: var(--text-muted);
      color: var(--text-muted);
    }
  }
  /* "Running skill /xxx" line beneath user bubbles. The `/<name>`
     fragment reuses the thinking-shimmer keyframe to convey the
     same in-progress feeling. */
  .running-skill {
    margin-top: 0.5em;
    font-size: var(--text-meta);
    color: var(--text-muted);
    display: inline-flex;
    align-items: center;
    gap: 0.4em;
    font-weight: 300;
  }
  .running-label {
    color: var(--text-muted);
  }
  .skill-shimmer {
    font-family: "SF Mono", Menlo, Consolas, monospace;
    background: linear-gradient(
      90deg,
      var(--text-faint) 0%,
      var(--text) 50%,
      var(--text-faint) 100%
    );
    background-size: 200% 100%;
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
    color: transparent;
    animation: thinking-shimmer 2.4s ease-in-out infinite;
  }
  @media (prefers-reduced-motion: reduce) {
    .skill-shimmer {
      animation: none;
      -webkit-text-fill-color: var(--text);
      color: var(--text);
    }
  }
  .footnote {
    margin-top: 0.4em;
    font-size: 0.8em;
    color: var(--text-muted);
    font-style: italic;
  }
  .tool-calls {
    /* Symmetric vertical spacing so the entry sits neatly between
       adjacent markdown paragraphs — top gap was previously 0,
       leaving the entry cramped against the line above it. */
    margin: 0.7em 0;
    display: flex;
    flex-direction: column;
    gap: 0.45em;
  }
</style>
