// Hardcoded skill fixtures for Phase 1 UI shell. Replaced in Phase 2
// once filesystem discovery and watching land.

import type { Skill } from "./types";

export const PHASE_1_FIXTURES: Skill[] = [
  {
    id: "claude:commit",
    name: "commit",
    source: "claude",
    origin: "~/.claude/commands/commit.md",
    description:
      "Commit staged/unstaged changes using conventional commits, grouping related work",
    arguments: [],
    allowedTools: ["Bash(git *)"],
    context: "inline",
    shell: "bash",
    userInvocable: true,
    hideFromSkillTool: false,
    body: "(fixture body)",
    frontmatter: {},
  },
  {
    id: "claude:pr",
    name: "pr",
    source: "claude",
    origin: "~/.claude/commands/pr.md",
    description: "Push committed changes and open a pull request",
    arguments: [],
    allowedTools: [],
    context: "inline",
    shell: "bash",
    userInvocable: true,
    hideFromSkillTool: false,
    body: "(fixture body)",
    frontmatter: {},
  },
  {
    id: "cursor:cursor-review",
    name: "cursor-review",
    source: "cursor",
    origin: "~/.cursor/skills-cursor/cursor-review/SKILL.md",
    description:
      "Run a Cursor agent code review on all changes in the current branch vs main/master. Auto-fixes CRITICAL issues; surfaces ADVISORY items for decision.",
    arguments: [],
    allowedTools: [],
    context: "inline",
    shell: "bash",
    userInvocable: true,
    hideFromSkillTool: false,
    body: "(fixture body)",
    frontmatter: {},
  },
  {
    id: "claude:review",
    name: "review",
    source: "claude",
    origin: "~/.claude/commands/review.md",
    description: "Review a pull request",
    arguments: [],
    allowedTools: [],
    context: "inline",
    shell: "bash",
    userInvocable: true,
    hideFromSkillTool: false,
    body: "(fixture body)",
    frontmatter: {},
  },
  {
    id: "codex:entropy-check",
    name: "entropy-check",
    source: "codex",
    origin: "~/.codex/prompts/entropy-check.md",
    description:
      "Audit the current branch for architectural drift — shallow modules, convention violations, missing tests, help/tool sync gaps",
    arguments: [],
    allowedTools: [],
    context: "inline",
    shell: "bash",
    userInvocable: true,
    hideFromSkillTool: false,
    body: "(fixture body)",
    frontmatter: {},
  },
  {
    id: "claude:start",
    name: "start",
    source: "claude",
    origin: "~/.claude/commands/start.md",
    description:
      "Start a new piece of work — sets up branch, fetches Jira ticket, briefs on methodology",
    arguments: [],
    allowedTools: [],
    context: "inline",
    shell: "bash",
    userInvocable: true,
    hideFromSkillTool: false,
    body: "(fixture body)",
    frontmatter: {},
  },
  {
    id: "local:interface-first",
    name: "interface-first",
    source: "local",
    origin: "~/.clive/skills/interface-first/SKILL.md",
    description:
      "Design the interface and write tests against it before any implementation — enforces TDD with an explicit contract approval gate",
    arguments: [],
    allowedTools: [],
    context: "inline",
    shell: "bash",
    userInvocable: true,
    hideFromSkillTool: false,
    body: "(fixture body)",
    frontmatter: {},
  },
  {
    id: "claude:debug",
    name: "debug",
    source: "claude",
    origin: "~/.claude/commands/debug.md",
    description: "Read and analyze debug logs for troubleshooting",
    arguments: [],
    allowedTools: [],
    context: "inline",
    shell: "bash",
    userInvocable: true,
    hideFromSkillTool: false,
    body: "(fixture body)",
    frontmatter: {},
  },
  {
    id: "local:grill-me",
    name: "grill-me",
    source: "local",
    origin: "~/.clive/skills/grill-me/SKILL.md",
    description:
      "Interview me relentlessly about every aspect of a plan until shared understanding",
    arguments: [],
    allowedTools: [],
    context: "inline",
    shell: "bash",
    userInvocable: true,
    hideFromSkillTool: false,
    body: "(fixture body)",
    frontmatter: {},
  },
  {
    id: "claude:fork-task",
    name: "fork-task",
    source: "claude",
    origin: "~/.claude/skills/fork-task/SKILL.md",
    description: "Fork a focused sub-task to a delegate (fork-mode example)",
    arguments: [],
    allowedTools: [],
    context: "fork",
    shell: "bash",
    userInvocable: true,
    hideFromSkillTool: false,
    body: "(fixture body)",
    frontmatter: {},
  },
];
