// Render-time chat types. Deliberately mirrors the Vercel AI SDK's
// UI message protocol — a chat turn is an assistant or user message,
// an assistant message is a list of typed parts (text / tool / step-start),
// a user message is a flat string with optional attachments.
//
// At the *runtime* layer we consume SDK `TextStreamPart` events directly
// (re-exported as `ChatStreamPart` below). The chat-store reducer maps
// those into `UIMessagePart` updates. This split mirrors the upstream backend's
// shared-types layout: runtime in SDK shapes, render in our own types.

import type { TextStreamPart, ToolSet } from "ai";

export type ChatStreamPart = TextStreamPart<ToolSet>;

export interface TextPart {
  type: "text";
  text: string;
  state?: "streaming" | "done";
}

export interface ToolPart {
  type: `tool-${string}`;
  toolCallId: string;
  state:
    | "input-streaming"
    | "input-available"
    | "output-available"
    | "output-error";
  input?: unknown;
  output?: unknown;
  errorText?: string;
}

export interface StepStartPart {
  type: "step-start";
}

export type UIMessagePart = TextPart | ToolPart | StepStartPart;

export interface UIAttachment {
  filename: string;
  mediaType: string;
  sizeBytes: number;
}

export interface UIAssistantMessage {
  id: string;
  role: "assistant";
  parts: UIMessagePart[];
  createdAt: string;
}

/** Lifecycle state of a skill invocation:
 *    - "running": materialise() has been called but hasn't resolved
 *      yet (variable substitution + shell expansion + permission
 *      prompts still pending). UI shows a shimmering "Running skill
 *      /xxx" line beneath the bubble.
 *    - "done": materialise resolved (success or denied). Indicator
 *      hidden.
 *  Absent on messages that didn't invoke a skill. */
export type SkillRunStatus = "running" | "done";

/** Captured at send-time when the user's input ends in a recognised
 *  `/skill` invocation. Rendered as a chip + chevron above the user
 *  bubble; the materialised body is what the model received in
 *  addition to the literal content. */
export interface SkillInvocationMeta {
  /** Skill name as resolved at send-time (e.g. "commit"). */
  name: string;
  /** Source family — drives the chip badge styling. */
  source: "claude" | "cursor" | "codex" | "local";
  /** "inline" (Phase 3) or "fork" (Phase 6). */
  context: "inline" | "fork";
  /** Raw arguments the user typed after the command name. */
  args: string;
  /** When context === "fork", the run-id of the spawned delegate run.
   *  Phase 6 sets this; Phase 3 leaves it undefined. */
  runId?: string;
}

export interface UIUserMessage {
  id: string;
  role: "user";
  content: string;
  attachments?: UIAttachment[];
  createdAt: string;
  /** Present only when the message invokes a skill. Drives the chip
   *  + drawer rendering. */
  skillInvocation?: SkillInvocationMeta;
  /** Materialised skill body — what the model received joined to
   *  `content` for this turn. Persisted alongside the user message so
   *  re-rendering the conversation later doesn't have to re-execute
   *  any shell blocks. */
  skillExpandedBody?: string;
  /** Lifecycle of the skill invocation — only meaningful while the
   *  turn is live; replayed history is implicitly "done". */
  skillStatus?: SkillRunStatus;
  /** When true, this user-role message was generated by the system rather
   *  than typed by the user. The orchestrator sees it as user input (so
   *  the AI SDK can treat it as a turn trigger) but the UI renders it
   *  with distinct styling so the human user understands it wasn't their
   *  message. Used by the post-delegate-completion notification flow:
   *  when a background delegate finishes, a synthetic user message
   *  carrying the completion details fires a new orchestrator turn. */
  systemEvent?: boolean;
}

export type UIChatTurn = UIAssistantMessage | UIUserMessage;
